### ISSUE TITLE
Ahahahahaha

### ISSUE THREAD

**Issue by rexim** [CherniakYura/olive.c#1]
This is pathetic my dude :)

**Comment by its-the-shrimp** [comment]
This repository does bring a sense of dejavu...

**Comment by cherniaky** [comment]
@rexim yes, it kinda is

**Comment by rexim** [comment]
@CherniakYura jfyi, stripping off my name from my source code is in direct violation of MIT license. Just putting it here so we are on the same page and understand what exactly you are doing in here. :)

**Comment by cherniaky** [comment]
@rexim Added your MIT license to files. I guess I will do the same for all your projects, that I rewrote. Every time I watched your video I coded in parallel, so there is already a bunch of stuff. Спасибо за твой контент

**Comment by rexim** [comment]
@CherniakYura here is a more ethical strategy to boost up your portfolio. Instead of taking Open Source projects and presenting them as yours, try to submit Pull Requests to them. Fix a bug, implement and a feature, etc. Once your changes are accepted you can add to your CV: "I contributed to project X".

I personally rarely accept any contributions to my projects these days, cause I don't really have resources to do that. But that strategy works for any Open Source projects. You may even try to target specific project that will look good in your resume. And it also gives you real world experience in software development.

**Comment by cherniaky** [comment]
@rexim thanks for the suggestion. It was not for my portfolio or anything, I had only learning purposes in mind. The fact that I have this repo is only to demonstrate that I understand everything that is written in it

**Comment by laurentiuNiculae** [comment]
> @rexim thanks for the suggestion. It was not for my portfolio or anything, I had only learning purposes in mind

No, you had in mind another project from Tsoding as part of your LinkedIn Portfolio. XD XD

**Comment by rexim** [comment]
Yeah, dude. We all saw your LinkedIn. It looks pretty cool ngl :)

**Comment by cherniaky** [comment]
> > @rexim thanks for the suggestion. It was not for my portfolio or anything, I had only learning purposes in mind
> 
> No, you had in mind another project from Tsoding as part of your LinkedIn Portfolio. XD XD

Yes, I did this, and I added the original license in place

**Comment by cherniaky** [comment]
Anyway sorry for this stuff

**Comment by rexim** [comment]
Alright-alright, but I'll be watching you (=_= )

**Comment by slavnycoder** [comment]
cringe
